# Generated by Django 3.2.23 on 2024-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=30)),
                ('oemail', models.CharField(max_length=30)),
                ('ophone', models.IntegerField(max_length=10)),
                ('opassword', models.CharField(max_length=30)),
            ],
        ),
    ]
