# Generated by Django 3.2.23 on 2024-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examples',
            old_name='opassword',
            new_name='ocity',
        ),
        migrations.AlterField(
            model_name='examples',
            name='ophone',
            field=models.IntegerField(),
        ),
    ]
